### ISSUE TITLE
360 video Error

### ISSUE THREAD

**Issue by cliffgr** [googlecodelabs/vr_view_app_101#2]
Samsung s6

05-20 16:38:56.491 25351-25478/com.google.devrel.vrviewapp E/OpenGLRenderer: GL error:  Out of memory!
05-20 16:41:06.961 30937-31038/com.google.devrel.vrviewapp E/AndroidRuntime: FATAL EXCEPTION: GLThread 920
                                                                             Process: com.google.devrel.vrviewapp, PID: 30937
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.vr.sdk.widgets.video.VideoTexture.getIsTextureSet()' on a null object reference
                                                                                 at com.google.vr.sdk.widgets.video.VrVideoPlayerInternal.prepareFrame(VrVideoPlayerInternal.java:318)
                                                                                 at com.google.vr.sdk.widgets.video.VrVideoRenderer.onDrawFrame(VrVideoRenderer.java:57)
                                                                                 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
                                                                                 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)
05-20 16:41:07.061 30937-31040/com.google.devrel.vrviewapp E/ion: ioctl c0044901 failed with code -1: Invalid argument

**Comment by dvallieres** [comment]
Did you ever find the issue?
