### ISSUE TITLE
Vr Video Widget calling method on null object. 

### ISSUE THREAD

**Issue by dvallieres** [googlecodelabs/vr_view_app_101#4]
I get this error 1 out of every 10 runs, I am using the Widget as advertised. It happens right
before the VR PANO is loaded. I track the error to internal classes that google has provided.
This is the complete stack trace. 
Someone else opened a ticket over this issue but cancelled it soon after, not sure why. 

I am using Samsung S5.

If I succesfully load the video once, I can reload it and not reproduce the error.

The error seems to be completely random, as said before 1 out of 10 runs this 
error will crash my program. 

It seems to happen right after backgroundVideoLoaderTask.execute(fileUri); is run.
backgroundVideoLoaderTask is a VideoLoaderTask. 

Any ideas would be appreciated. 

06-24 11:32:01.021 20171-20238/com.example.android.dependonthis E/AndroidRuntime:
FATAL EXCEPTION: GLThread 14504

Process: com.example.android.dependonthis, PID: 20171

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.vr.sdk.widgets.video.VideoTexture.getIsTextureSet()' on a null object reference
                                                                                      at 
com.google.vr.sdk.widgets.video.VrVideoPlayerInternal.prepareFrame(VrVideoPlayerInternal.java:318)
                                                                                      at com.google.vr.sdk.widgets.video.VrVideoRenderer.onDrawFrame(VrVideoRenderer.java:57)
                                                                                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1561)
                                                                                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1278)

**Comment by RamIndani** [comment]
@dvallieres Did you find why this exception occurs?
