### ISSUE TITLE
Google Vr Video View Error

### ISSUE THREAD

**Issue by Sabinay-android** [googlecodelabs/vr_view_app_101#5]
after videoWidgetView.loadVideo(Uri.parse("http://192.168.0.115:8888/googlemap/MageComp.mp4"));
or
videoWidgetView..loadVideoFromAsset("3dtest3.mp4");
// 3dtest3.mp4 stored in my asset forlder

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.vr.sdk.widgets.video.VideoTexture.getIsTextureSet()' on a null object reference
                                                                           at com.google.vr.sdk.widgets.video.VrVideoPlayerInternal.prepareFrame(VrVideoPlayerInternal.java:318)
                                                                           at com.google.vr.sdk.widgets.video.VrVideoRenderer.onDrawFrame(VrVideoRenderer.java:57)
                                                                           at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1566)
                                                                           at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

**Comment by RamIndani** [comment]
I was here to report the exact same exception. Please share if you find solution, I will also do the same.

**Comment by RamIndani** [comment]
I think these two are related 
https://github.com/googlecodelabs/vr_view_app_101/issues/2

**Comment by Sabinay-android** [comment]
@RamIndani , Yap , in some devices its works better but in some cases it facing this error.

**Comment by RamIndani** [comment]
@Sabinay-android around four similar bugs are reported and closed but none of them provide any resolution.

**Comment by RamIndani** [comment]
I have Samsung S3 and Samsung S6 both crashes with this message almost 99% of the time and not always.
